<?php defined( 'ABSPATH' ) || exit;
/**
 * Pest encyclopedia: CPT zad_pest at /pests/{slug}/ (the CPT's own rewrite rule — no page is generated by itself; no archive).
 * The owner writes the content; this file builds the structure: fields, identification attributes (used by the question-based identifier),
 * a single template, a [zad_pests] list shortcode for a normal Page, schema (Article + FAQPage on the theme's single @graph) and breadcrumbs.
 * Nothing is invented: an empty field prints nothing.
 */

/* ---------------------------------------------- settings ---------------------------------------------- */

add_action( 'zad_tools_register_settings', function () {
	zt_register_settings( 'pests', 'الموسوعة والمعرّف', array(
		array( 'key' => 'colors', 'label' => 'ألوان الحشرة (مفتاح | الاسم | رمز)', 'type' => 'table', 'default' => "brown | بني | 🟤\nblack | أسود | ⚫\nred | أحمر أو برتقالي | 🟠\nwhite | أبيض أو شفاف | ⚪\ngray | رمادي | 🔘\ngreen | أخضر | 🟢\nyellow | أصفر | 🟡" ),
		array( 'key' => 'sizes', 'label' => 'الحجم (مفتاح | الاسم | رمز)', 'type' => 'table', 'default' => "tiny | أقل من 3 مم | ·\nsmall | من 3 إلى 10 مم | •\nmedium | من 1 إلى 3 سم | ●\nlarge | أكبر من 3 سم | ⬤", 'desc' => 'الفئات من أمر التنفيذ.' ),
		array( 'key' => 'places', 'label' => 'المكان (مفتاح | الاسم | رمز)', 'type' => 'table', 'default' => "kitchen | مطبخ | 🍳\nbath | حمام | 🚿\nbed | سرير | 🛏️\nwood | خشب | 🪵\ngarden | حديقة | 🌿\ntank | خزان | 💧\nclothes | ملابس | 👕" ),
		array( 'key' => 'signs', 'label' => 'العلامة الأوضح (مفتاح | الاسم | رمز)', 'type' => 'table', 'default' => "bites | لدغات | 🩹\nsawdust | نشارة خشب | 🪵\ndroppings | فضلات | 🟫\nwings_left | أجنحة مرمية | 🪰\nmud | طين على الجدار | 🧱" ),
		array( 'key' => 'weights', 'label' => 'وزن كل سؤال في التطابق (السؤال | الوزن)', 'type' => 'table', 'default' => "place | 1\nsize | 1\ncolor | 1\nwings | 1\nsign | 1", 'desc' => 'أوزان متساوية افتراضياً (لا أفضلية لسؤال). place size color wings sign.' ),
		array( 'key' => 'min_match', 'label' => 'أقل نسبة تطابق لاعتبار النتيجة «قوية» (%)', 'type' => 'number', 'default' => 60, 'min' => 1, 'max' => 100, 'approval' => true, 'source' => 'قيمة مقترحة من عندي — دون ذلك نعرض «ابعتلنا صورة» بدل الجزم' ),
		array( 'key' => 'max_results', 'label' => 'عدد الحشرات الأقرب المعروضة', 'type' => 'number', 'default' => 3, 'min' => 1, 'max' => 6, 'source' => 'من أمر التنفيذ (أقرب 3 حشرات)' ),
		array( 'key' => 'min_pests', 'label' => 'أقل عدد حشرات منشورة (ببيانات تعريف) لفتح المعرّف', 'type' => 'number', 'default' => 3, 'min' => 1, 'max' => 50, 'source' => 'شرط تقني: المعرّف يعرض 3 نتائج، فلا يفتح بأقل من 3' ),
		array( 'key' => 'index_page', 'label' => 'صفحة «موسوعة الحشرات» (للمسار في الأعلى)', 'type' => 'page', 'default' => 0, 'required' => false, 'desc' => 'صفحة عادية بك فيها <code>[zad_pests]</code>؛ فارغ = يظهر المسار الرئيسية ← اسم الحشرة.' ),
		array( 'key' => 'seed_names', 'label' => 'أسماء لإنشاء مسودات فارغة (سطر لكل حشرة)', 'type' => 'textarea', 'default' => "الصراصير\nالنمل\nالنمل الأبيض\nبق الفراش\nالفئران", 'required' => false, 'desc' => 'زر «إنشاء المسودات» في قائمة الموسوعة يضيف ما ينقص كمسودات بحقول فاضية (لا تُنشر).' ),
	) );
} );

/** Options of a vocabulary setting → array( key => array( label, icon ) ). */
function zt_pest_vocab( $name ) {
	$out = array();
	foreach ( zt_table( zt_opt( 'pests.' . $name ) ) as $r ) { if ( count( $r ) >= 2 && '' !== $r[0] ) { $out[ sanitize_key( $r[0] ) ] = array( $r[1], $r[2] ?? '' ); } }
	return $out;
}
function zt_pest_wings() { return array( 'yes' => array( 'نعم', '🪽' ), 'no' => array( 'لا', '🚫' ), 'some' => array( 'أحيانًا', '🔁' ) ); }
function zt_pest_attr_groups() { return array( 'place' => 'places', 'size' => 'sizes', 'color' => 'colors', 'sign' => 'signs' ); }

/* ---------------------------------------------- CPT ---------------------------------------------- */

add_action( 'init', function () {
	register_post_type( 'zad_pest', array(
		'labels' => array( 'name' => 'موسوعة الحشرات', 'singular_name' => 'حشرة', 'add_new' => 'إضافة حشرة', 'add_new_item' => 'إضافة حشرة جديدة', 'edit_item' => 'تعديل الحشرة', 'all_items' => 'كل الحشرات', 'menu_name' => 'موسوعة الحشرات' ),
		'public' => true, 'show_ui' => true, 'show_in_rest' => false, 'has_archive' => false, 'exclude_from_search' => false, 'menu_icon' => 'dashicons-book-alt', 'menu_position' => 27,
		'rewrite' => array( 'slug' => 'pests', 'with_front' => false ), 'supports' => array( 'title', 'editor', 'excerpt', 'thumbnail', 'author', 'revisions' ),
	) );
}, 6 );

/** One-time rewrite flush after the plugin version that introduced the CPT (activation does not run on an upgrade). */
add_action( 'init', function () {
	if ( get_option( 'zt_pests_rules' ) !== 'v1' ) { flush_rewrite_rules( false ); update_option( 'zt_pests_rules', 'v1', false ); }
}, 99 );

/* ---------------------------------------------- meta box ---------------------------------------------- */

add_action( 'add_meta_boxes', function () { add_meta_box( 'zt_pest', 'بيانات الحشرة', 'zt_pest_box', 'zad_pest', 'normal', 'high' ); } );

function zt_pest_activity() { return array( 'night' => 'ليلي', 'day' => 'نهاري', 'both' => 'ليلي ونهاري' ); }
function zt_pest_danger() { return array( 'low' => 'منخفض', 'medium' => 'متوسط', 'high' => 'مرتفع' ); }

function zt_pest_box( $post ) {
	wp_nonce_field( 'zt_pest_box', 'zt_pest_nonce' );
	$g = function ( $k ) use ( $post ) { return get_post_meta( $post->ID, '_zp_' . $k, true ); };
	echo '<p class="description">الحقول الفارغة لا تظهر في الصفحة. أضف صورة بارزة واكتب لها <strong>نصاً بديلاً</strong> من مكتبة الوسائط. خصائص التعريف (آخر الصندوق) هي ما يطابقه المعرّف بالأسئلة.</p><table class="form-table"><tbody>';
	echo '<tr><th>الأسماء الشائعة في السعودية</th><td><input class="large-text" name="zp[names]" value="' . esc_attr( $g( 'names' ) ) . '" placeholder="مفصولة بفاصلة"></td></tr>';
	echo '<tr><th>الاسم العلمي</th><td><input class="large-text" dir="ltr" name="zp[sci]" value="' . esc_attr( $g( 'sci' ) ) . '"></td></tr>';
	echo '<tr><th>علامات وجودها</th><td><textarea class="large-text" rows="3" name="zp[signs]" placeholder="سطر لكل علامة">' . esc_textarea( $g( 'signs' ) ) . '</textarea></td></tr>';
	echo '<tr><th>أماكن تواجدها</th><td><textarea class="large-text" rows="3" name="zp[places]" placeholder="سطر لكل مكان">' . esc_textarea( $g( 'places' ) ) . '</textarea></td></tr>';
	echo '<tr><th>النشاط</th><td><select name="zp[activity]"><option value="">—</option>';
	foreach ( zt_pest_activity() as $k => $l ) { echo '<option value="' . esc_attr( $k ) . '"' . selected( $g( 'activity' ), $k, false ) . '>' . esc_html( $l ) . '</option>'; }
	echo '</select> <input name="zp[season]" value="' . esc_attr( $g( 'season' ) ) . '" placeholder="الموسم (نص حر)"></td></tr>';
	echo '<tr><th>مستوى الخطر</th><td><select name="zp[danger]"><option value="">—</option>';
	foreach ( zt_pest_danger() as $k => $l ) { echo '<option value="' . esc_attr( $k ) . '"' . selected( $g( 'danger' ), $k, false ) . '>' . esc_html( $l ) . '</option>'; }
	echo '</select></td></tr>';
	echo '<tr><th>الوقاية</th><td><textarea class="large-text" rows="3" name="zp[prevent]" placeholder="سطر لكل نصيحة">' . esc_textarea( $g( 'prevent' ) ) . '</textarea></td></tr>';
	echo '<tr><th>الخدمة المرتبطة</th><td><input type="text" dir="ltr" name="zp[service]" value="' . esc_attr( $g( 'service' ) ) . '" placeholder="رقم صفحة الخدمة"> <span class="description">زر «اطلب الخدمة» ورابط داخلي.</span></td></tr>';
	echo '<tr><th>أسئلة شائعة</th><td><textarea class="large-text" rows="5" name="zp[faq]" placeholder="السؤال | الجواب (سطر لكل سؤال)">' . esc_textarea( $g( 'faq' ) ) . '</textarea></td></tr>';
	echo '<tr><th>خصائص التعريف</th><td>';
	foreach ( zt_pest_attr_groups() as $q => $vocab ) {
		$have = (array) $g( 'a_' . $q ); $title = array( 'place' => 'المكان', 'size' => 'الحجم', 'color' => 'اللون', 'sign' => 'العلامة' )[ $q ];
		echo '<p><strong>' . esc_html( $title ) . ':</strong> ';
		foreach ( zt_pest_vocab( $vocab ) as $k => $v ) { echo '<label style="margin-inline-end:12px"><input type="checkbox" name="zp[a_' . esc_attr( $q ) . '][]" value="' . esc_attr( $k ) . '"' . checked( in_array( $k, $have, true ), true, false ) . '> ' . esc_html( $v[0] ) . '</label>'; }
		echo '</p>';
	}
	echo '<p><strong>أجنحة:</strong> <select name="zp[a_wings]"><option value="">—</option>';
	foreach ( zt_pest_wings() as $k => $v ) { echo '<option value="' . esc_attr( $k ) . '"' . selected( $g( 'a_wings' ), $k, false ) . '>' . esc_html( $v[0] ) . '</option>'; }
	echo '</select> <span class="description">«أحيانًا» تطابق أي إجابة.</span></p></td></tr></tbody></table>';
}

add_action( 'save_post_zad_pest', function ( $id ) {
	if ( ! isset( $_POST['zt_pest_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['zt_pest_nonce'] ) ), 'zt_pest_box' ) || ! current_user_can( 'edit_post', $id ) || wp_is_post_autosave( $id ) ) { return; }
	$in = isset( $_POST['zp'] ) ? (array) wp_unslash( $_POST['zp'] ) : array();
	foreach ( array( 'names', 'sci', 'season' ) as $k ) { update_post_meta( $id, '_zp_' . $k, sanitize_text_field( $in[ $k ] ?? '' ) ); }
	foreach ( array( 'signs', 'places', 'prevent', 'faq' ) as $k ) { update_post_meta( $id, '_zp_' . $k, sanitize_textarea_field( $in[ $k ] ?? '' ) ); }
	update_post_meta( $id, '_zp_activity', isset( zt_pest_activity()[ $in['activity'] ?? '' ] ) ? $in['activity'] : '' );
	update_post_meta( $id, '_zp_danger', isset( zt_pest_danger()[ $in['danger'] ?? '' ] ) ? $in['danger'] : '' );
	update_post_meta( $id, '_zp_service', absint( zt_digits_en( (string) ( $in['service'] ?? '' ) ) ) ?: '' );
	foreach ( zt_pest_attr_groups() as $q => $vocab ) { update_post_meta( $id, '_zp_a_' . $q, array_values( array_intersect( array_map( 'sanitize_key', (array) ( $in[ 'a_' . $q ] ?? array() ) ), array_keys( zt_pest_vocab( $vocab ) ) ) ) ); }
	update_post_meta( $id, '_zp_a_wings', isset( zt_pest_wings()[ $in['a_wings'] ?? '' ] ) ? $in['a_wings'] : '' );
	delete_transient( 'zt_pest_cfg' );
} );
add_action( 'transition_post_status', function ( $n, $o, $post ) { if ( 'zad_pest' === $post->post_type ) { delete_transient( 'zt_pest_cfg' ); } }, 10, 3 );

/* ---------------------------------------------- seeding (empty drafts, on click) ---------------------------------------------- */

add_action( 'admin_menu', function () {
	add_submenu_page( 'edit.php?post_type=zad_pest', 'إنشاء المسودات', 'إنشاء المسودات', 'edit_posts', 'zt-pest-seed', 'zt_pest_seed_page' );
} );
function zt_pest_seed_names() { return array_values( array_unique( array_filter( array_map( 'trim', preg_split( '/\r\n|\n|\r/', (string) zt_opt( 'pests.seed_names' ) ) ), 'strlen' ) ) ); }
function zt_pest_seed_page() {
	if ( ! current_user_can( 'edit_posts' ) ) { return; }
	echo '<div class="wrap" dir="rtl"><h1>إنشاء مسودات الحشرات</h1>';
	if ( isset( $_GET['made'] ) ) { echo '<div class="notice notice-success"><p>أُنشئت ' . (int) $_GET['made'] . ' مسودة.</p></div>'; }
	$names = zt_pest_seed_names();
	echo '<p>تُنشأ مسودة فارغة لكل اسم لا توجد له حشرة بنفس الاسم (القائمة من «أدوات زاد ← الموسوعة والمعرّف»). المسودات لا تظهر للزوار حتى تنشرها بعد كتابة المحتوى.</p><ul style="list-style:disc;padding-inline-start:20px">';
	foreach ( $names as $n ) { echo '<li>' . esc_html( $n ) . ( zt_pest_exists( $n ) ? ' — <em>موجودة</em>' : '' ) . '</li>'; }
	echo '</ul><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">';
	wp_nonce_field( 'zt_pest_seed' ); echo '<input type="hidden" name="action" value="zt_pest_seed">'; submit_button( 'إنشاء المسودات الناقصة' ); echo '</form></div>';
}
function zt_pest_exists( $title ) { $q = get_posts( array( 'post_type' => 'zad_pest', 'post_status' => 'any', 'title' => $title, 'numberposts' => 1, 'fields' => 'ids', 'no_found_rows' => true ) ); return (bool) $q; }
add_action( 'admin_post_zt_pest_seed', function () {
	if ( ! current_user_can( 'edit_posts' ) ) { wp_die( 'غير مسموح' ); }
	check_admin_referer( 'zt_pest_seed' );
	$made = 0;
	foreach ( zt_pest_seed_names() as $n ) { if ( ! zt_pest_exists( $n ) ) { $id = wp_insert_post( array( 'post_type' => 'zad_pest', 'post_status' => 'draft', 'post_title' => $n ) ); if ( $id && ! is_wp_error( $id ) ) { $made++; } } }
	wp_safe_redirect( add_query_arg( array( 'post_type' => 'zad_pest', 'page' => 'zt-pest-seed', 'made' => $made ), admin_url( 'edit.php' ) ) );
	exit;
} );

/* ---------------------------------------------- data ---------------------------------------------- */

function zt_pest_lines( $s ) { return array_values( array_filter( array_map( 'trim', preg_split( '/\r\n|\n|\r/', (string) $s ) ), 'strlen' ) ); }

/** Everything about one pest, escaped nowhere (the renderers escape). */
function zt_pest_data( $id ) {
	$g = function ( $k ) use ( $id ) { return get_post_meta( $id, '_zp_' . $k, true ); };
	$arr = function ( $k ) use ( $g ) { $v = $g( $k ); return is_array( $v ) ? array_values( array_filter( array_map( 'strval', $v ), 'strlen' ) ) : array(); }; // get_post_meta() gives '' for an unset field
	$svc = (int) $g( 'service' );
	$thumb = get_post_thumbnail_id( $id );
	return array(
		'id' => (int) $id, 'name' => get_the_title( $id ), 'url' => get_permalink( $id ), 'names' => array_values( array_filter( array_map( 'trim', explode( ',', str_replace( '،', ',', (string) $g( 'names' ) ) ) ), 'strlen' ) ),
		'sci' => (string) $g( 'sci' ), 'signs' => zt_pest_lines( $g( 'signs' ) ), 'places' => zt_pest_lines( $g( 'places' ) ), 'activity' => (string) $g( 'activity' ), 'season' => (string) $g( 'season' ),
		'danger' => (string) $g( 'danger' ), 'prevent' => zt_pest_lines( $g( 'prevent' ) ),
		'service' => ( $svc && 'publish' === get_post_status( $svc ) ) ? array( function_exists( 'zad_card_title' ) ? zad_card_title( $svc ) : get_the_title( $svc ), get_permalink( $svc ) ) : null,
		'faq' => array_values( array_filter( array_map( function ( $r ) { return count( $r ) >= 2 ? array( $r[0], implode( ' | ', array_slice( $r, 1 ) ) ) : null; }, zt_table( $g( 'faq' ) ) ) ) ),
		'a' => array( 'place' => $arr( 'a_place' ), 'size' => $arr( 'a_size' ), 'color' => $arr( 'a_color' ), 'sign' => $arr( 'a_sign' ), 'wings' => (string) $g( 'a_wings' ) ),
		'img' => $thumb ? (string) wp_get_attachment_image_url( $thumb, 'medium' ) : '', 'alt' => $thumb ? (string) get_post_meta( $thumb, '_wp_attachment_image_alt', true ) : '',
	);
}

/* ---------------------------------------------- single page ---------------------------------------------- */

add_filter( 'template_include', function ( $tpl ) {
	if ( is_singular( 'zad_pest' ) ) { $t = locate_template( 'zad-tools/pest-single.php' ); return $t ? $t : ZT_DIR . 'templates/pest-single.php'; }
	return $tpl;
}, 30 );

function zt_pest_body( $id ) {
	$d = zt_pest_data( $id ); $act = zt_pest_activity(); $dan = zt_pest_danger();
	echo '<section class="sec"><div class="wrap wrap--narrow zt-pest">';
	if ( $d['img'] ) { echo '<figure class="zt-pest__img"><img src="' . esc_url( $d['img'] ) . '" alt="' . esc_attr( $d['alt'] ) . '" width="360" height="270" loading="eager" fetchpriority="high"></figure>'; }
	$facts = array();
	if ( $d['names'] ) { $facts[] = array( 'الأسماء الشائعة', implode( '، ', $d['names'] ) ); }
	if ( '' !== $d['sci'] ) { $facts[] = array( 'الاسم العلمي', '<i dir="ltr">' . esc_html( $d['sci'] ) . '</i>' ); }
	if ( isset( $act[ $d['activity'] ] ) ) { $facts[] = array( 'النشاط', esc_html( $act[ $d['activity'] ] . ( '' !== $d['season'] ? ' — ' . $d['season'] : '' ) ) ); }
	elseif ( '' !== $d['season'] ) { $facts[] = array( 'الموسم', esc_html( $d['season'] ) ); }
	if ( isset( $dan[ $d['danger'] ] ) ) { $facts[] = array( 'مستوى الخطر', esc_html( $dan[ $d['danger'] ] ) ); }
	if ( $facts ) {
		echo '<dl class="zt-facts">';
		foreach ( $facts as $f ) { echo '<div><dt>' . esc_html( $f[0] ) . '</dt><dd>' . ( 'الاسم العلمي' === $f[0] ? $f[1] : esc_html( $f[1] ) ) . '</dd></div>'; } // phpcs:ignore WordPress.Security.EscapeOutput -- escaped above
		echo '</dl>';
	}
	$content = trim( (string) get_post_field( 'post_content', $id ) );
	if ( '' !== $content ) { echo '<div class="zt-pest__content">' . apply_filters( 'the_content', $content ) . '</div>'; } // phpcs:ignore WordPress.Security.EscapeOutput
	foreach ( array( array( 'signs', 'علامات وجودها' ), array( 'places', 'أماكن تواجدها' ), array( 'prevent', 'الوقاية' ) ) as $s ) {
		if ( $d[ $s[0] ] ) { echo '<h2>' . esc_html( $s[1] ) . '</h2><ul>'; foreach ( $d[ $s[0] ] as $l ) { echo '<li>' . esc_html( $l ) . '</li>'; } echo '</ul>'; }
	}
	if ( $d['faq'] ) {
		echo '<h2>أسئلة شائعة</h2><div class="zt-faq">';
		foreach ( $d['faq'] as $f ) { echo '<details><summary>' . esc_html( $f[0] ) . '</summary><p>' . esc_html( $f[1] ) . '</p></details>'; }
		echo '</div>';
	}
	echo '<div class="zt-actions">';
	if ( $d['service'] ) { echo '<a class="btn btn--accent" href="' . esc_url( $d['service'][1] ) . '" data-zt-event="tool_cta">' . esc_html( $d['service'][0] ) . '</a>'; }
	$wa = zt_wa_number();
	if ( $wa ) { echo '<a class="btn btn--wa" target="_blank" rel="noopener" href="' . esc_url( zt_wa_url( $wa, zt_wa_message( 'عندي مشكلة ' . $d['name'] . ' وأحتاج فحصاً.', '' ) ) ) . '">اسأل على واتساب</a>'; }
	echo '</div></div></section>';
}

/** Breadcrumbs: الرئيسية › الموسوعة (the owner's Page, if chosen) › name. */
add_filter( 'zad_current_crumbs', function ( $c ) {
	if ( ! is_singular( 'zad_pest' ) ) { return $c; }
	$out = array( array( 'الرئيسية', home_url( '/' ) ) ); $ix = (int) zt_opt( 'pests.index_page' );
	if ( $ix && 'publish' === get_post_status( $ix ) ) { $out[] = array( get_the_title( $ix ), get_permalink( $ix ) ); }
	$out[] = array( get_the_title(), '' );
	return $out;
} );

/** Article + FAQPage on the theme's single @graph; reviewer / author like the rest of the site's content. */
add_filter( 'zad_schema_page_nodes', function ( $nodes, $id ) {
	if ( 'zad_pest' !== get_post_type( $id ) ) { return $nodes; }
	return zt_pest_schema( $nodes, zt_pest_data( $id ), $id );
}, 10, 2 );

function zt_pest_schema( $nodes, $d, $id ) {
	$u = $d['url']; $home = home_url( '/' ); $person = function_exists( 'zsc_person_node' ) ? zsc_person_node( (int) get_post_field( 'post_author', $id ) ) : null;
	$rev = null; $rid = function_exists( 'zad_opt' ) ? (int) zad_opt( 'zad_reviewer', 0 ) : 0; if ( $rid && function_exists( 'zsc_person_node' ) ) { $rev = zsc_person_node( $rid ); }
	$about = array( '@type' => 'Taxon', 'name' => $d['name'] ); $alt = array_merge( $d['names'], '' !== $d['sci'] ? array( $d['sci'] ) : array() ); if ( $alt ) { $about['alternateName'] = $alt; }
	$art = array( '@type' => 'Article', '@id' => $u . '#article', 'headline' => mb_substr( $d['name'], 0, 110 ), 'url' => $u, 'mainEntityOfPage' => array( '@id' => $u . '#webpage' ), 'isPartOf' => array( '@id' => $u . '#webpage' ),
		'datePublished' => get_post_time( 'c', true, $id ), 'dateModified' => get_post_modified_time( 'c', true, $id ), 'publisher' => array( '@id' => $home . '#organization' ), 'inLanguage' => 'ar', 'about' => $about );
	if ( $d['img'] ) { $art['image'] = $d['img']; }
	if ( $person ) { $art['author'] = array( '@id' => $person['@id'] ); }
	foreach ( $nodes as $i => $n ) { if ( isset( $n['@id'] ) && $u . '#webpage' === $n['@id'] && $rev ) { $nodes[ $i ]['reviewedBy'] = array( '@id' => $rev['@id'] ); $nodes[ $i ]['lastReviewed'] = get_post_modified_time( 'Y-m-d', true, $id ); } }
	$nodes[] = $art; if ( $person ) { $nodes[] = $person; } if ( $rev && ( ! $person || $rev['@id'] !== $person['@id'] ) ) { $nodes[] = $rev; }
	if ( $d['faq'] ) {
		$ents = array(); foreach ( $d['faq'] as $f ) { $ents[] = array( '@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => $f[1] ) ); }
		$nodes[] = array( '@type' => 'FAQPage', '@id' => $u . '#faq', 'mainEntity' => $ents, 'isPartOf' => array( '@id' => $u . '#webpage' ) );
	}
	return $nodes;
}

/* ---------------------------------------------- [zad_pests] — the list for the owner's Page ---------------------------------------------- */

add_shortcode( 'zad_pests', function () {
	$q = get_posts( array( 'post_type' => 'zad_pest', 'post_status' => 'publish', 'numberposts' => 200, 'orderby' => 'title', 'order' => 'ASC', 'no_found_rows' => true ) );
	if ( ! $q ) { return ''; }
	$h = '<ul class="zt-cards">';
	foreach ( $q as $p ) { $d = zt_pest_data( $p->ID ); $h .= '<li class="zt-cards__i"><a class="zt-cards__a" href="' . esc_url( $d['url'] ) . '">' . ( $d['img'] ? '<img src="' . esc_url( $d['img'] ) . '" alt="' . esc_attr( $d['alt'] ) . '" width="72" height="72" loading="lazy">' : '' ) . '<span><strong>' . esc_html( $d['name'] ) . '</strong>' . ( $d['sci'] ? '<em dir="ltr">' . esc_html( $d['sci'] ) . '</em>' : '' ) . '</span></a></li>'; }
	return $h . '</ul>';
} );
add_action( 'wp_enqueue_scripts', function () {
	global $post;
	if ( is_singular( 'zad_pest' ) || ( $post instanceof WP_Post && has_shortcode( (string) $post->post_content, 'zad_pests' ) ) ) { wp_enqueue_style( 'zt-tool', ZT_URL . 'assets/css/zt-tool.css', array(), ZT_VERSION ); }
} );
