// Drives the REAL post edit screen (classic form; core admin JS/CSS are absent in the trimmed test core so only the box logic is checked): counter + warnings, search filters, save.
import { createRequire } from 'node:module'; import { execFileSync } from 'node:child_process';
const require = createRequire(import.meta.url); const { chromium } = require('playwright');
const WPX = process.env.WPX || '/tmp/wpsite', BASE = process.env.WPX_URL || 'http://127.0.0.1:8099', dir = process.argv[2] || '/tmp';
const php = (c) => execFileSync('php', ['-r', `require "${WPX}/wp-load.php"; ${c}`], { encoding: 'utf8' }).trim();
let fail = 0, n = 0; const ok = (x, m) => { n++; if (!x) { fail++; console.log('FAIL:', m); } };
const id = php('echo get_page_by_path("spray-price",OBJECT,"zad_faq")->ID;');
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 1300, height: 1000 } })).newPage(); const errs = []; p.on('pageerror', (e) => { if (!/Unexpected token '<'|wp is not defined|jQuery|\$ is not defined|tinymce|reading 'editor'/.test(String(e))) errs.push(String(e)); });
await p.goto(BASE + '/wp-login.php'); await p.fill('#user_login', 'admin'); await p.fill('#user_pass', 'pass1234'); await p.click('#wp-submit'); await p.waitForLoadState();
await p.goto(`${BASE}/wp-admin/post.php?post=${id}&action=edit`); await p.waitForSelector('#zad-fa-text');
ok(!(await p.$('#postexcerpt')), 'native excerpt box is gone'); ok(!!(await p.$('#zad_faq_meta')), 'side box present');
const warn = () => p.textContent('#zad-fa-warn'), cnt = () => p.textContent('#zad-fa-count');
ok((await cnt()) === '8', 'initial counter = 8 (' + (await cnt()) + ')');
await p.fill('#zad-fa-text', ''); ok((await cnt()) === '0' && /فارغة/.test(await warn()), 'empty answer: counter 0 + warning');
await p.fill('#zad-fa-text', Array.from({ length: 61 }, (_, i) => 'كلمة' + i).join(' ')); ok((await cnt()) === '61' && /أطول من 60/.test(await warn()), '61 words: warning');
await p.fill('#zad-fa-text', Array.from({ length: 60 }, (_, i) => 'كلمة' + i).join(' ')); ok((await cnt()) === '60' && (await warn()) === '', '60 words: no warning');
await p.fill('#zad-fa-text', 'السعر يحدده الفني بعد المعاينة المجانية حسب المساحة.');
const opts = async (s) => p.$$eval(`#${s} option`, (o) => o.map((x) => x.textContent));
const allS = await opts('zad_faq_service_link'), allA = await opts('zad_faq_article');
ok(allS.length >= 3 && allS.includes('مكافحة حشرات بالرياض') && allS.includes('تنظيف مكيفات بالرياض') && allS.some((t) => /مسودة/.test(t)), 'service list = all service types (zad_service/cleaning/pest_control, drafts marked) (' + allS.join('|') + ')');
await p.fill('[data-for=zad_faq_service_link]', 'خزانات'); ok(JSON.stringify(await opts('zad_faq_service_link')) === JSON.stringify(['— بدون —', 'تنظيف خزانات بالرياض']), 'service search filters');
await p.selectOption('#zad_faq_service_link', { label: 'تنظيف خزانات بالرياض' });
await p.fill('[data-for=zad_faq_service_link]', ''); ok((await opts('zad_faq_service_link')).length === allS.length && (await p.inputValue('#zad_faq_service_link')) !== '0', 'clearing search restores the list, keeps the choice');
await p.fill('[data-for=zad_faq_article]', 'التحضير'); await p.selectOption('#zad_faq_article', { label: 'دليل التحضير للرش' });
await p.fill('[name=zad_faq_service_lbl]', 'اطلب الخدمة الآن');
await p.screenshot({ path: dir + '/box-screen.png', fullPage: true });
await Promise.all([p.waitForNavigation(), p.click('#publish, #save-post, input[name=save]')]).catch(async () => { await p.evaluate(() => document.getElementById('post').submit()); await p.waitForLoadState(); });
const j = JSON.parse(php('$i=' + id + '; echo json_encode(array(get_post_field("post_excerpt",$i),(int)get_post_meta($i,"_zad_faq_service_link",true),get_post_meta($i,"_zad_faq_service_lbl",true),(int)get_post_meta($i,"_zad_faq_article",true)),JSON_UNESCAPED_UNICODE);'));
ok(j[0] === 'السعر يحدده الفني بعد المعاينة المجانية حسب المساحة.', 'saved excerpt: ' + j[0]); ok(j[1] > 0 && j[2] === 'اطلب الخدمة الآن' && j[3] > 0, 'saved links/label: ' + JSON.stringify(j));
console.log(n + ' checks, ' + fail + ' failed', errs.length ? errs : ''); await b.close(); process.exit(fail ? 1 : 0);
